-- drop table if exists author CASCADE;
-- drop table if exists book CASCADE;

-- create table author (
--     id bigint generated by default as identity,
--     name varchar(100),
--     primary key (id));
--
-- create table book (
--     id bigint generated by default as identity,
--     title varchar(100),
--     primary key (id));

-- alter table book add foreign key (author_id) references author;

insert into author (name)
values('Ivan Morozov');
insert into author (name)
values('Vladislav Pavlov');
insert into author (name)
values('Andrey Serov');

insert into book (title, author_id)
values('First', '1');
insert into book (title, author_id)
values('Red', '2');
insert into book (title, author_id)
values('Craft', '3');