drop table if exists author cascade;

create table if not exists author (
    id bigint generated by default as identity,
    name varchar(100),
    primary key (id));

-- create table if not exists author (
--     id bigserial primary key,
--     name character varying(100),
--     primary key (id)
--     );
