drop table if exists book cascade;

create table if not exists book (
    id bigint generated by default as identity,
    title varchar(100),
    author_id bigint,
    primary key (id));

alter table book add foreign key (author_id) references author;

-- create table if not exists book (
--     id bigserial primary key,
--     title character varying(100),
--     foreign key (author_id) references author(id)
--     );
